#
# Use this environment to configure use a local Kubernetes cluster to build wave containers
#
# - add "dev-k8s" to the list of environments defined in the 'micronautEnvs' property in the "gradle.property" file
# - create the directory "${HOME}/.wave/build-workspace"
# - change the Kubernetes context in the config below with the one matching your installation
# - create a namespace in your local Kubernetes cluster named "wave-local"
#
wave:
  build:
    debug: true
    workspace: "${HOME}/.wave/build-workspace"
    k8s:
      configPath: "${HOME}/.kube/config"
      context: 'docker-desktop'
      namespace: 'wave-local'
      storage:
        mountPath: "${HOME}/.wave/build-workspace"
      resources:
        requests:
          memory: '2400Mi'
      tolerations:
        enabled: true
        arm64:
          - key : 'arch'
            value : 'arm64'
            operator : 'Equal'
            effect : 'NoSchedule'
          - key : 'arch'
            value : 'aarch64'
            operator : 'Equal'
            effect : 'NoSchedule'
...
