---
micronaut:
  application:
    name: demo
  server:
    port: 9090
---
netty:
  default:
    allocator:
      max-order: 3
---
wave:
  arch: 'x86_64'
---
datasources:
  default:
    url: "${TOWER_DB_URL}"
    driverClassName: "${TOWER_DB_DRIVER}"
    username: "${TOWER_DB_USER}"
    password: "${TOWER_DB_PASSWORD}"
    dialect: H2
---
tower:
  crypto:
    secretKey: "6Lc407kUAAAAAPCb10a_5czoIYbB1zjtMdnGYnF7"
...
