wave:
  blobCache:
    enabled: true
    baseUrl: "https://wave-cache-stage-cloudflare.seqera.io"
    storage:
      bucket: "s3://wave-cache-stage"
      region: "auto"
      endpoint: "https://cb55d6dbe24ce84a89c9df291b7486e4.r2.cloudflarestorage.com"
      accessKey: "193f1312979c9c09f11f4aaeede3173d"
      secretKey: "af9dfa2ea57d4ec08ab4cf1c948b8b3f9c1a32c2893ba743873710589ddc0d4c"
