---
micronaut:
  application:
    name: demo
  server:
    port: 9090
---
netty:
  default:
    allocator:
      max-order: 3
---
wave:
  arch: 'x86_64'
  debug: true
  allowAnonymous: true
  server:
      url: 'https://reg.ngrok.io'
  build:
    image: "195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/kaniko:0.1.0"
    dockerMode: true
    workspace: 'build-workspace'
    repository: "195996028523.dkr.ecr.eu-west-1.amazonaws.com/wave/build"
...
