---
micronaut:
  application:
    name: demo
  server:
    port: 9090
---
netty:
  default:
    allocator:
      max-order: 3
---
wave:
  arch: 'x86_64'
...
datasources:
  default:
    url: "${TOWER_DB_URL:`jdbc:h2:file:./.db/h2/tower;AUTO_SERVER=TRUE`}"
    driverClassName: "${TOWER_DB_DRIVER:`org.h2.Driver`}"
    username: "${TOWER_DB_USER:`sa`}"
    password: "${TOWER_DB_PASSWORD:}"
