wave:
  debug: true
  build:
    k8s:
      configPath: "${HOME}/.kube/config"
      context: 'docker-desktop'
      namespace: 'wave-local'
      storage:
        mountPath: "/Users/pditommaso/nf-tower-stack/wave/k8s/data"
    workspace: "/Users/pditommaso/nf-tower-stack/wave/k8s/data"
