---
micronaut:
  application:
    name: demo
  server:
    port: 9090
---
netty:
  default:
    allocator:
      max-order: 3
---
towerreg:
  arch : x86_64
  layerPath: pack/layers/layer.json
  storage:
    maximum-size: 1000
    expire-after: 1h
