name: Wave Open Api CI
on:
  push:
    branches:
      - '**'
      - '!refs/tags/.*'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - mkdocs.yml
      - '*.md'
      - .github/workflows/website_preview.yml
      - .github/workflows/website_deploy.yml
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - mkdocs.yml
      - '*.md'
      - .github/workflows/website_preview.yml
      - .github/workflows/website_deploy.yml
jobs:
  release-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.TOWER_CI_AWS_ACCESS}}
          aws-secret-access-key: ${{secrets.secrets.TOWER_CI_AWS_SECRET}}
          aws-region: eu-west-1

      - name : Login to Amazon ECR
        id : login-ecr
        uses : aws-actions/amazon-ecr-login@v1

      - name: Release docs
        if: "contains(github.event.head_commit.message, '[release docs]')"
        run: |
          bash typespec/tag-and-push-docs.sh
