---
name: Typespec_Validation

on:
  push:
    branches:
      - '**'
    paths :
      - 'typespec/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'typespec/**'

permissions:
  contents: read

jobs:
  typespec_validation:
    name: validate typespec files
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name : Setup Node.js environment
        uses : actions/setup-node@v4
        with :
          node-version : '20.9.0'

      - name : Install tsp
        run : npm install -g @typespec/compiler

      - name : Validate tsp files
        run : |
          cd typespec
          tsp install
          tsp compile .

      - name: Release
        if: "contains(github.event.head_commit.message, '[release]')"
        run: |
          bash typespec/tag-and-push-docs.sh
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
          AWS_ACCESS_KEY_ID: ${{secrets.TOWER_CI_AWS_ACCESS}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.TOWER_CI_AWS_SECRET}}
          GITHUB_TOKEN: ${{ secrets.GH_SEQERA_TOKEN }}
